CREATE TABLE Guild (
	ID SERIAL PRIMARY KEY,
	Name TEXT UNIQUE NOT NULL,
	Description TEXT,
	Emblem TEXT,
	Raid INT NOT NULL DEFAULT 0,
	Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MemberLimit INT NOT NULL DEFAULT 30,
	DemonPortalAct INT NOT NULL DEFAULT 1,
	DemonPortalHealth INT NOT NULL DEFAULT 1,
	Catapult INT NOT NULL DEFAULT 0 CHECK (Catapult < 4),
	PetId INT,
	HydraCurrentLife INT NOT NULL,
	Attacking INT REFERENCES Guild (ID)
);

-- Everything related to the Membership of a player to a guild
CREATE TABLE GuildMember (
	ID SERIAL PRIMARY KEY,
	Guild INT NOT NULL REFERENCES Guild (ID),
	Rank INT NOT NULL,
	Joined TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	LastActive TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	IsDefending BOOL NOT NULL DEFAULT FALSE,
	IsAttacking BOOL NOT NULL DEFAULT FALSE,
	-- The amount of times we fought against the hydra today
	HydraFoughtCount INT NOT NULL DEFAULT 0,
	-- Last time we fought with pet against the hydra
	HydraLastFought TIMESTAMP,
	-- Last time we fought in the portal
	PortalLastFought TIMESTAMP
);

-- The guild upgrades a player has for himself
CREATE TABLE GuildUpgrade {
    ID SERIAL PRIMARY KEY,
	Treasure INT NOT NULL DEFAULT 0,
	Instructor INT NOT NULL DEFAULT 0,
	PetLvl INT NOT NULL DEFAULT 0,
};


CREATE TABLE Item (
    ID SERIAL PRIMARY KEY,
	Enchantment INT NOT NULL DEFAULT 0,
	ItemTyp INT NOT NULL,
	
	Effect1 INT NOT NULL DEFAULT 0, 
	Effect2 INT NOT NULL DEFAULT 0,
	
	Ident INT NOT NULL DEFAULT 0,
	Count INT NOT NULL DEFAULT 0,
	Expires TIMESTAMP,
	
	GemType INT NOT NULL DEFAULT 0,
	GemPower INT NOT NULL DEFAULT 0,

	Class INT NOT NULL DEFAULT 0,
	
	AtrTyp1 INT NOT NULL DEFAULT 0,
	AtrVal1 INT NOT NULL DEFAULT 0,
	AtrTyp2 INT NOT NULL DEFAULT 0,
	AtrVal2 INT NOT NULL DEFAULT 0,
	AtrTyp3 INT NOT NULL DEFAULT 0,
	AtrVal3 INT NOT NULL DEFAULT 0,
	
	ModelID INT NOT NULL,
	
	Silver INT NOT NULL,
	Mushrooms INT NOT NULL
);

CREATE Table Bag (
	ID SERIAL PRIMARY KEY,
	pos1 INT REFERENCES ITEM(ID),
	pos2 INT REFERENCES ITEM(ID),
	pos3 INT REFERENCES ITEM(ID),
	pos4 INT REFERENCES ITEM(ID),
	pos5 INT REFERENCES ITEM(ID)
);

CREATE TABLE Attributes (
    ID SERIAL PRIMARY KEY,
	Strength INT NOT NULL DEFAULT 0,
	Dexterity INT NOT NULL DEFAULT 0,
	Intelligence INT NOT NULL DEFAULT 0,
	Stamina INT NOT NULL DEFAULT 0,
	Luck INT NOT NULL DEFAULT 0
);

CREATE TABLE LoginData (
	ID SERIAL PRIMARY KEY,
	LowerName TEXT UNIQUE NOT NULL,
	Mail TEXT UNIQUE NOT NULL,
	PWHash TEXT NOT NULL,
	SessionID Text NOT NULL,
	CryptoID Text UNIQUE NOT NULL,
	CryptoKey Text NOT NULL,
	LoginCount INT NOT NULL DEFAULT 0
);

CREATE TABLE Quest (
    ID SERIAL PRIMARY KEY,
	Flavour1 INT NOT NULL DEFAULT 1,
	Flavour2 INT NOT NULL DEFAULT 1,
	Monster INT NOT NULL,
	Location INT NOT NULL,
	Length INT NOT NULL,
	Item Int REFERENCES Item(ID) ON DELETE CASCADE
);

CREATE TABLE Tavern (
    ID SERIAL PRIMARY KEY,

	Quest1 INT NOT NULL REFERENCES Quest(ID) ON DELETE CASCADE,
	Quest2 INT NOT NULL REFERENCES Quest(ID) ON DELETE CASCADE,
	Quest3 INT NOT NULL REFERENCES Quest(ID) ON DELETE CASCADE,
	
	TFA INT NOT NULL DEFAULT 600,
	BeerDrunk INT NOT NULL DEFAULT 0,
	QuickSand INT NOT NULL DEFAULT 60,
	
	DiceGamesRemaining INT NOT NULL DEFAULT 10,
	DiceGameNextFree TIMESTAMP
);

CREATE TABLE Character (
	ID SERIAL PRIMARY KEY,
	Name TEXT UNIQUE NOT NULL,
	Class INT NOT NULL,
	Level INT NOT NULL DEFAULT 1,
	Experience BIGINT NOT NULL DEFAULT 0,
	Honor INT NOT NULL DEFAULT 300,
	Silver BIGINT NOT NULL DEFAULT 100,
	Mushrooms INT NOT NULL DEFAULT 30,
	
	Bag INT NOT NULL REFERENCES Bag(ID),
	Attributes INT NOT NULL REFERENCES Attributes (ID) ON DELETE CASCADE,
	AttributesBought INT NOT NULL REFERENCES Attributes (ID) ON DELETE CASCADE,
	LoginData INT NOT NULL REFERENCES LoginData (ID) ON DELETE CASCADE,
	Tavern INT NOT NULL REFERENCES Tavern(ID) ON DELETE CASCADE,
	Guild INT REFERENCES GuildMember (ID) ON DELETE CASCADE
);

CREATE INDEX HoF ON Character (Honor DESC, ID ASC);

CREATE TABLE ChatMessage (
	ID SERIAL PRIMARY KEY,
	Sender INT REFERENCES CHARACTER(ID),
	Send TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Guild INT REFERENCES Guild(ID),
	Whisper INT REFERENCES Character(ID),
	Messafe TEXT NOT NULL,
	IsGlobal BOOLEAN NOT NULL
);


CREATE MATERIALIZED VIEW HoFView AS
SELECT
	id,
	ROW_NUMBER(
) OVER ( ORDER BY HONOR DESC,
		ID) AS Rank
FROM
	Character
ORDER BY
	HONOR DESC,
	ID; 
	

CREATE UNIQUE INDEX HoF2 on HoFView(id);
CREATE UNIQUE INDEX HoF3 on HoFView(rank);


CREATE TABLE ChatMessage (
	ID SERIAL PRIMARY KEY,
	Sender INT REFERENCES CHARACTER(ID),
	Send TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Guild INT REFERENCES Guild(ID),
	Whisper INT REFERENCES Character(ID),
	Messafe TEXT NOT NULL,
	IsGlobal BOOLEAN NOT NULL
);

